version: "3"
services:
  app:
    build: .
    image: nop-status-server:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      - "PORT=${PORT}"
      - "STATUS=${STATUS}"
      - "MESSAGE=${MESSAGE}"
